### ISSUE TITLE
Multiple parameter assignments during pattern matching does not work

### ISSUE THREAD

**Issue by AGembeeded** [typhoon-hil/model-converter#2]
As an example, Active Full Wave Rectifier (AFWRm) can be used.
At the present one parameter is being set:
     ctrl_src= "Internal modulator";
I've tried to add the following:
     S1 = "3";
     S2 = "9";
During model conversion an exception occurs.
The added properties are correct, I've tested them by replacing the " ctrl_src= "Internal modulator"; " with " S1 = "3"; " or " S2 = "9" ; " and it works.

**Comment by pojzn** [comment]
Issue resolved in [the following commit.](https://github.com/typhoon-hil/model-converter/commit/0edd193ff93fb14c9308e40d99485e06e4643551)
